name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'latest'
env:
  DH_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DH_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DH_USERNAME }}
        password: ${{ env.DH_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-laravelapp:${{ github.event.inputs.version }}
        build-args: VERSION=${{ github.event.inputs.version }}