name: Test Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'latest'
env:
  DH_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DH_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  CONTAINER_NAME: laravel-app-run
jobs:
  test:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ubuntu
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          echo hello
          echo world