name: Test Pipeline

on: workflow_dispatch
env:
  DH_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DH_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
  CONTAINER_NAME: laravel-app-run
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: EC2 Test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ubuntu
        key: ${{ env.EC2_SSH_KEY }}
        script: |
          echo hello
          echo world
          echo ${{ CONTAINER_NAME }}